"""Compatibility entry point for the cleaned twininfo production pipeline."""
from __future__ import annotations

from .pipeline import (
    ALL_CONDITIONS,
    AUGMENTED_VISUAL_COMPARISON_CONDITIONS,
    MAIN_CONDITIONS,
    PHASE_CONDITIONS,
    SF_CONDITIONS,
    STABILIZED_VISUAL_CONTROL_CONDITIONS,
    TRAJECTORY_COMPARISON_CONDITIONS as _TRAJECTORY_COMPARISON_CONDITIONS,
    TRAJECTORY_CONTROL_CONDITIONS as _TRAJECTORY_CONTROL_CONDITIONS,
    PipelineConfig,
    main,
    run_pipeline,
)

PHASE_COMPARISON_CONDITIONS = PHASE_CONDITIONS
SF_COMPARISON_CONDITIONS = SF_CONDITIONS
TRAJECTORY_COMPARISON_CONDITIONS = _TRAJECTORY_COMPARISON_CONDITIONS
TRAJECTORY_CONTROL_CONDITIONS = _TRAJECTORY_CONTROL_CONDITIONS

__all__ = [
    "ALL_CONDITIONS",
    "AUGMENTED_VISUAL_COMPARISON_CONDITIONS",
    "MAIN_CONDITIONS",
    "PHASE_COMPARISON_CONDITIONS",
    "PipelineConfig",
    "SF_COMPARISON_CONDITIONS",
    "STABILIZED_VISUAL_CONTROL_CONDITIONS",
    "TRAJECTORY_COMPARISON_CONDITIONS",
    "TRAJECTORY_CONTROL_CONDITIONS",
    "main",
    "run_pipeline",
]


if __name__ == "__main__":
    main()
