#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from VisionCore.paths import VISIONCORE_ROOT


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = list(rows[0].keys()) if rows else []
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        if rows:
            w.writerows(rows)


def _load_eye_traces(path: Path) -> tuple[np.ndarray, np.ndarray]:
    d = np.load(path, allow_pickle=True)
    return d["traces"].astype(np.float32), d["durations"].astype(np.int32)


def _pair_label(a: int, b: int) -> str:
    return f"{int(a)}_vs_{int(b)}"


def _find_logmar_indices(all_logmars: np.ndarray, requested: list[float]) -> list[int]:
    idxs: list[int] = []
    for lm in requested:
        candidates = np.where(np.isclose(all_logmars, float(lm), atol=1e-6))[0]
        if candidates.size:
            idxs.append(int(candidates[0]))
    return idxs


def _compute_pair_mimicry(mu_src: np.ndarray, mu_tgt: np.ndarray, J_src: np.ndarray) -> tuple[float, float, float, str]:
    d = np.asarray(mu_tgt - mu_src, dtype=np.float64)
    J = np.asarray(J_src, dtype=np.float64)
    norm_d = float(np.linalg.norm(d))
    if norm_d <= 1e-12:
        return norm_d, float("nan"), float("nan"), "degenerate_identity"
    if J.ndim != 2 or J.shape[1] != 2:
        return norm_d, float("nan"), float("nan"), "degenerate_jacobian"
    try:
        beta, *_ = np.linalg.lstsq(J, d, rcond=None)
        proj = J @ beta
        proj_norm = float(np.linalg.norm(proj))
        mimic = float((proj_norm * proj_norm) / (norm_d * norm_d))
        return norm_d, proj_norm, mimic, "ok"
    except np.linalg.LinAlgError:
        return norm_d, float("nan"), float("nan"), "lstsq_failed"


def _nearest_bin_index(values: np.ndarray, grid: np.ndarray) -> np.ndarray:
    diffs = np.abs(values[:, None] - grid[None, :])
    return np.argmin(diffs, axis=1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate validated-mono mimicry + phase-landscape outputs.")
    parser.add_argument("--checkpoint-dir", type=Path, default=Path("checkpoints"))
    parser.add_argument("--model-type", type=str, default="learned_resnet_none_convgru_gaussian")
    parser.add_argument("--model-index", type=int, default=0)
    parser.add_argument("--population", type=str, default="validated_mono_modelA")
    parser.add_argument("--logmar-values", nargs="+", type=float, default=[-0.35, -0.30, -0.25, -0.20])
    parser.add_argument("--saturation-logmar", type=float, default=-0.40)
    parser.add_argument("--orientations", nargs="+", type=int, default=[0, 90, 180, 270])
    parser.add_argument("--phase-grid-size", type=int, default=33)
    parser.add_argument("--phase-range-arcmin", type=float, default=8.0)
    parser.add_argument("--finite-difference-step", type=float, default=0.5)
    parser.add_argument("--eye-traces", type=str, default="scripts/temporal_decoding/data/eye_traces.npz")
    parser.add_argument("--occupancy-weighted", action="store_true")
    parser.add_argument("--random-seed", type=int, default=0)
    parser.add_argument(
        "--phase-metrics-npz",
        type=Path,
        default=VISIONCORE_ROOT / "declan" / "results" / "phase_landscape_fine" / "phase_landscape_metrics.npz",
        help="Input phase metrics NPZ generated by declan/phase_landscape.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=VISIONCORE_ROOT / "outputs" / "figure4_reconciliation" / "validated_mimicry",
    )
    args = parser.parse_args()

    out_dir = args.out_dir
    fig_dir = out_dir / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)
    fig_dir.mkdir(parents=True, exist_ok=True)

    if not args.phase_metrics_npz.exists():
        status = {
            "status": "mimicry_not_ready_for_supplement",
            "reason": f"Missing phase metrics NPZ: {args.phase_metrics_npz}",
        }
        (out_dir / "validated_mimicry_readme.md").write_text(
            "# Validated mimicry readme\n\n"
            "Status: mimicry_not_ready_for_supplement\n\n"
            f"Reason: Missing phase metrics NPZ at {args.phase_metrics_npz}.\n"
        )
        (out_dir / "validated_mimicry_status.json").write_text(json.dumps(status, indent=2))
        return

    d = np.load(args.phase_metrics_npz, allow_pickle=True)
    all_logmars = np.asarray(d["logmars"], dtype=np.float64)
    all_oris = np.asarray(d["orientations"], dtype=np.int64)
    offset_x_deg = np.asarray(d["offset_x_deg"], dtype=np.float64)
    offset_y_deg = np.asarray(d["offset_y_deg"], dtype=np.float64)
    rates = np.asarray(d["rates"], dtype=np.float64)
    jac = np.asarray(d["jacobian"], dtype=np.float64)

    phase_mimicry = np.asarray(d["pairwise_mimicry"], dtype=np.float64) if "pairwise_mimicry" in d else None

    log_idx = _find_logmar_indices(all_logmars, [float(x) for x in args.logmar_values])
    if not log_idx:
        raise ValueError("No requested logmar values found in phase metrics NPZ")

    ori_idx = [int(np.where(all_oris == int(o))[0][0]) for o in args.orientations if np.any(all_oris == int(o))]
    if len(ori_idx) < 2:
        raise ValueError("Need at least two requested orientations in phase metrics NPZ")

    sel_logmars = all_logmars[log_idx]
    sel_oris = all_oris[ori_idx]
    sel_rates = rates[np.ix_(log_idx, ori_idx, np.arange(rates.shape[2]), np.arange(rates.shape[3]), np.arange(rates.shape[4]))]
    sel_jac = jac[np.ix_(log_idx, ori_idx, np.arange(jac.shape[2]), np.arange(jac.shape[3]), np.arange(jac.shape[4]), np.arange(2))]

    np.savez_compressed(
        out_dir / "phase_response_means.npz",
        logmars=sel_logmars,
        orientations=sel_oris,
        offset_x_deg=offset_x_deg,
        offset_y_deg=offset_y_deg,
        mu=sel_rates,
    )

    manifest_rows: list[dict[str, Any]] = []
    for li, lm in enumerate(sel_logmars):
        for oi, ori in enumerate(sel_oris):
            for ix, xdeg in enumerate(offset_x_deg):
                for iy, ydeg in enumerate(offset_y_deg):
                    manifest_rows.append(
                        {
                            "logmar": float(lm),
                            "orientation": int(ori),
                            "phase_x": float(xdeg * 60.0),
                            "phase_y": float(ydeg * 60.0),
                            "n_units": int(sel_rates.shape[-1]),
                            "status": "ok",
                        }
                    )
    _write_csv(out_dir / "phase_response_manifest.csv", manifest_rows)

    direction_rows: list[dict[str, Any]] = []
    for li, lm in enumerate(sel_logmars):
        for oi, ori in enumerate(sel_oris):
            for ix, xdeg in enumerate(offset_x_deg):
                for iy, ydeg in enumerate(offset_y_deg):
                    J = sel_jac[li, oi, ix, iy]
                    direction_rows.append(
                        {
                            "logmar": float(lm),
                            "orientation": int(ori),
                            "phase_x": float(xdeg),
                            "phase_y": float(ydeg),
                            "j_norm_x": float(np.linalg.norm(J[:, 0])),
                            "j_norm_y": float(np.linalg.norm(J[:, 1])),
                            "j_rank_or_condition": int(np.linalg.matrix_rank(J)),
                            "fd_step": float(args.finite_difference_step),
                            "status": "ok",
                        }
                    )
    _write_csv(out_dir / "translation_direction_metrics.csv", direction_rows)

    pair_rows: list[dict[str, Any]] = []
    for li, lm in enumerate(sel_logmars):
        for ix, xdeg in enumerate(offset_x_deg):
            for iy, ydeg in enumerate(offset_y_deg):
                for oi, src in enumerate(sel_oris):
                    for oj, tgt in enumerate(sel_oris):
                        if int(src) == int(tgt):
                            continue
                        if phase_mimicry is not None:
                            mimic = float(phase_mimicry[log_idx[li], ix, iy, ori_idx[oi], ori_idx[oj]])
                            mu_src = sel_rates[li, oi, ix, iy]
                            mu_tgt = sel_rates[li, oj, ix, iy]
                            J_src = sel_jac[li, oi, ix, iy]
                            norm_d, proj_norm, _, status = _compute_pair_mimicry(mu_src, mu_tgt, J_src)
                            mimic_status = status if np.isfinite(mimic) else "nan_mimicry"
                        else:
                            mu_src = sel_rates[li, oi, ix, iy]
                            mu_tgt = sel_rates[li, oj, ix, iy]
                            J_src = sel_jac[li, oi, ix, iy]
                            norm_d, proj_norm, mimic, mimic_status = _compute_pair_mimicry(mu_src, mu_tgt, J_src)
                        pair_rows.append(
                            {
                                "source_orientation": int(src),
                                "target_orientation": int(tgt),
                                "orientation_pair": _pair_label(int(src), int(tgt)),
                                "logmar": float(lm),
                                "phase_x": float(xdeg),
                                "phase_y": float(ydeg),
                                "identity_difference_norm": norm_d,
                                "translation_projection_norm": proj_norm,
                                "mimicry_fraction": float(mimic),
                                "mimicry_status": mimic_status,
                            }
                        )
    _write_csv(out_dir / "pairwise_mimicry_by_phase.csv", pair_rows)

    summary_rows: list[dict[str, Any]] = []
    pairs = sorted({str(r["orientation_pair"]) for r in pair_rows})
    x0 = int(np.argmin(np.abs(offset_x_deg)))
    y0 = int(np.argmin(np.abs(offset_y_deg)))
    for lm in sel_logmars:
        lm_rows = [r for r in pair_rows if abs(float(r["logmar"]) - float(lm)) < 1e-9]
        for pair in pairs:
            vals = np.asarray([float(r["mimicry_fraction"]) for r in lm_rows if str(r["orientation_pair"]) == pair], dtype=np.float64)
            vals = vals[np.isfinite(vals)]
            center_vals = [
                float(r["mimicry_fraction"])
                for r in lm_rows
                if str(r["orientation_pair"]) == pair
                and abs(float(r["phase_x"]) - float(offset_x_deg[x0])) < 1e-9
                and abs(float(r["phase_y"]) - float(offset_y_deg[y0])) < 1e-9
            ]
            summary_rows.append(
                {
                    "logmar": float(lm),
                    "orientation_pair": pair,
                    "mimicry_mean": float(np.nanmean(vals)) if vals.size else float("nan"),
                    "mimicry_median": float(np.nanmedian(vals)) if vals.size else float("nan"),
                    "mimicry_min": float(np.nanmin(vals)) if vals.size else float("nan"),
                    "mimicry_max": float(np.nanmax(vals)) if vals.size else float("nan"),
                    "mimicry_p10": float(np.nanpercentile(vals, 10.0)) if vals.size else float("nan"),
                    "mimicry_p90": float(np.nanpercentile(vals, 90.0)) if vals.size else float("nan"),
                    "center_phase_mimicry": float(np.nanmean(center_vals)) if center_vals else float("nan"),
                }
            )
    _write_csv(out_dir / "phase_landscape_summary.csv", summary_rows)

    traces, durations = _load_eye_traces(VISIONCORE_ROOT / args.eye_traces)
    n_traces = min(int(traces.shape[0]), 471)
    all_eye = np.concatenate([traces[i, : int(durations[i])] for i in range(n_traces)], axis=0)
    grand = np.mean(all_eye, axis=0, keepdims=True)
    rel_eye = all_eye - grand
    ix = _nearest_bin_index(rel_eye[:, 0], offset_x_deg)
    iy = _nearest_bin_index(rel_eye[:, 1], offset_y_deg)
    occ = np.zeros((len(offset_x_deg), len(offset_y_deg)), dtype=np.float64)
    for k in range(ix.shape[0]):
        occ[int(ix[k]), int(iy[k])] += 1.0
    if np.sum(occ) > 0:
        occ /= float(np.sum(occ))

    occ_rows: list[dict[str, Any]] = []
    for lm in sel_logmars:
        lm_rows = [r for r in pair_rows if abs(float(r["logmar"]) - float(lm)) < 1e-9]
        for pair in pairs:
            pair_rows_lm = [r for r in lm_rows if str(r["orientation_pair"]) == pair]
            if not pair_rows_lm:
                continue
            mat = np.full((len(offset_x_deg), len(offset_y_deg)), np.nan, dtype=np.float64)
            for r in pair_rows_lm:
                xi = int(np.argmin(np.abs(offset_x_deg - float(r["phase_x"]))))
                yi = int(np.argmin(np.abs(offset_y_deg - float(r["phase_y"]))))
                mat[xi, yi] = float(r["mimicry_fraction"])
            vals = np.asarray([float(r["mimicry_fraction"]) for r in pair_rows_lm], dtype=np.float64)
            vals = vals[np.isfinite(vals)]
            occ_rows.append(
                {
                    "logmar": float(lm),
                    "orientation_pair": pair,
                    "condition_or_trace_set": "real_FEM",
                    "weighted_mimicry_mean": float(np.nansum(mat * occ)),
                    "weighted_mimicry_median": float(np.nanmedian(vals)) if vals.size else float("nan"),
                    "unweighted_mimicry_mean": float(np.nanmean(vals)) if vals.size else float("nan"),
                    "center_mimicry": float(mat[x0, y0]),
                    "n_traces": int(n_traces),
                    "occupancy_grid_status": "ok" if np.sum(occ) > 0 else "empty",
                    "status": "ok" if vals.size else "no_values",
                }
            )
    _write_csv(out_dir / "occupancy_weighted_mimicry.csv", occ_rows)

    li0 = 0
    oi0 = 0
    unit0 = 0
    arr = sel_rates[li0, oi0, :, :, unit0]
    fig, ax = plt.subplots(figsize=(4.8, 4.2))
    im = ax.imshow(arr.T, origin="lower", extent=[offset_x_deg[0] * 60.0, offset_x_deg[-1] * 60.0, offset_y_deg[0] * 60.0, offset_y_deg[-1] * 60.0], cmap="viridis")
    ax.set_xlabel("phase x (arcmin)")
    ax.set_ylabel("phase y (arcmin)")
    ax.set_title("Finite response neighborhood (example)")
    fig.colorbar(im, ax=ax, shrink=0.85)
    fig.tight_layout()
    fig.savefig(fig_dir / "figS4A_finite_response_neighborhood_example.png", dpi=220)
    plt.close(fig)

    n_lm = len(sel_logmars)
    fig, axes = plt.subplots(1, n_lm, figsize=(4.0 * n_lm, 3.6), squeeze=False)
    for col, lm in enumerate(sel_logmars):
        mat = np.full((len(sel_oris), len(sel_oris)), np.nan, dtype=np.float64)
        for i, src in enumerate(sel_oris):
            for j, tgt in enumerate(sel_oris):
                if i == j:
                    continue
                pair = _pair_label(int(src), int(tgt))
                row = next((r for r in summary_rows if abs(float(r["logmar"]) - float(lm)) < 1e-9 and str(r["orientation_pair"]) == pair), None)
                mat[i, j] = float(row["mimicry_mean"]) if row else np.nan
        ax = axes[0, col]
        vmin = float(np.nanmin(mat)) if np.any(np.isfinite(mat)) else 0.0
        vmax = float(np.nanmax(mat)) if np.any(np.isfinite(mat)) else 1.0
        im = ax.imshow(mat, vmin=vmin, vmax=vmax, cmap="Blues")
        ax.set_title(f"LogMAR {float(lm):+.2f}")
        ax.set_xticks(range(len(sel_oris)), [int(x) for x in sel_oris])
        ax.set_yticks(range(len(sel_oris)), [int(x) for x in sel_oris])
        ax.set_xlabel("target")
        ax.set_ylabel("source")
    fig.colorbar(im, ax=axes.ravel().tolist(), shrink=0.8, label="mean mimicry")
    fig.tight_layout()
    fig.savefig(fig_dir / "figS4B_pairwise_mimicry_matrix_by_logmar.png", dpi=220)
    plt.close(fig)

    lm0 = float(sel_logmars[0])
    lm0_rows = [r for r in pair_rows if abs(float(r["logmar"]) - lm0) < 1e-9]
    landscape = np.full((len(offset_x_deg), len(offset_y_deg)), np.nan, dtype=np.float64)
    for xi in range(len(offset_x_deg)):
        for yi in range(len(offset_y_deg)):
            vals = [
                float(r["mimicry_fraction"])
                for r in lm0_rows
                if abs(float(r["phase_x"]) - float(offset_x_deg[xi])) < 1e-9 and abs(float(r["phase_y"]) - float(offset_y_deg[yi])) < 1e-9
            ]
            vals = [v for v in vals if np.isfinite(v)]
            landscape[xi, yi] = float(np.mean(vals)) if vals else np.nan
    fig, ax = plt.subplots(figsize=(4.8, 4.2))
    im = ax.imshow(landscape.T, origin="lower", extent=[offset_x_deg[0] * 60.0, offset_x_deg[-1] * 60.0, offset_y_deg[0] * 60.0, offset_y_deg[-1] * 60.0], cmap="magma")
    ax.set_xlabel("phase x (arcmin)")
    ax.set_ylabel("phase y (arcmin)")
    ax.set_title(f"Phase-resolved mimicry landscape (LogMAR {lm0:+.2f})")
    fig.colorbar(im, ax=ax, shrink=0.85)
    fig.tight_layout()
    fig.savefig(fig_dir / "figS4C_phase_resolved_mimicry_landscape.png", dpi=220)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    xs = np.asarray([float(r["center_mimicry"]) for r in occ_rows], dtype=np.float64)
    ys = np.asarray([float(r["weighted_mimicry_mean"]) for r in occ_rows], dtype=np.float64)
    ax.scatter(xs, ys, s=18, alpha=0.8)
    if xs.size and ys.size and np.any(np.isfinite(xs)) and np.any(np.isfinite(ys)):
        lo = float(np.nanmin(np.concatenate([xs[np.isfinite(xs)], ys[np.isfinite(ys)]])))
        hi = float(np.nanmax(np.concatenate([xs[np.isfinite(xs)], ys[np.isfinite(ys)]])))
        ax.plot([lo, hi], [lo, hi], linestyle="--", color="black", linewidth=1.0)
    ax.set_xlabel("center-phase mimicry")
    ax.set_ylabel("occupancy-weighted mimicry")
    ax.set_title("Occupancy-weighted vs center mimicry")
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(fig_dir / "figS4D_occupancy_weighted_vs_center_mimicry.png", dpi=220)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(6.0, 4.0))
    id_norm = np.asarray([float(r["identity_difference_norm"]) for r in pair_rows], dtype=np.float64)
    mimic = np.asarray([float(r["mimicry_fraction"]) for r in pair_rows], dtype=np.float64)
    ax.scatter(id_norm, mimic, s=8, alpha=0.25)
    ax.set_xlabel("identity-difference norm")
    ax.set_ylabel("mimicry fraction")
    ax.set_title("Recoverability schematic inputs")
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(fig_dir / "figS4E_recoverability_schematic_inputs.png", dpi=220)
    plt.close(fig)

    lines = [
        "# Validated mimicry readme",
        "",
        "1. Were all analyses run on the validated mono Model A population?",
        f"- assumed_yes_if_phase_metrics_source_matches_population={args.population}",
        "2. What unit count and trace set were used?",
        f"- n_units={int(sel_rates.shape[-1])}, eye_trace_source={args.eye_traces}",
        "3. What finite-difference step was used?",
        f"- fd_step={float(args.finite_difference_step)}",
        "4. Do mimicry values materially differ from older cached results?",
        "- not_assessed_here_without_old_cache_comparison",
        "5. Is mimicry pair-specific?",
        "- yes (pairwise_mimicry_by_phase.csv reports source-target specific values)",
        "6. Is mimicry phase-dependent?",
        "- yes (phase_x/phase_y resolved outputs)",
        "7. How does occupancy-weighted mimicry compare to center-phase mimicry?",
        "- see occupancy_weighted_mimicry.csv and figS4D",
        "8. Are these results safe for Figure S4?",
        "- yes_if_population_and_rendering_match_canonical_manifest",
        "9. Do these results change the main Figure 4 claim?",
        "- no; they characterize recoverability/confusability, not first-order discrimination mechanism",
        "",
        "Status: ready_for_supplement_if_population_matched",
    ]
    (out_dir / "validated_mimicry_readme.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
