#!/usr/bin/env python3
"""
Phase 1 FEM/V1 covariance analysis.

Tests whether foveal V1 shared variability during fixation is partly a
low-dimensional, image-conditioned reafferent covariance generated by self-motion.

Three linked analyses:
  Analysis 1: 2D FEM covariance geometry / derivative-code analysis
  Analysis 2: noise-correlation mixture / sign-flip replication
  Analysis 3: aggregation-scaling diagnostic

Usage (pilot):
    python scripts/run_phase1_fem_covariance.py \\
        --dataset-configs-path multi_basic_120_long_legacy.yaml \\
        --sessions Allen:2022-02-16 \\
        --use-cached-data \\
        --out-dir outputs/phase1_fem_covariance \\
        --bin-ms 10 \\
        --random-seed 12345 \\
        --run-covariance-geometry

Usage (full batch):
    python scripts/run_phase1_fem_covariance.py \\
        --dataset-configs-path multi_basic_120_long_legacy.yaml \\
        --sessions Allen:2022-02-16 Allen:2022-02-24 Allen:2022-03-04 Allen:2022-04-08 \\
        --use-cached-data \\
        --out-dir outputs/phase1_fem_covariance \\
        --bin-ms 10 \\
        --random-seed 12345 \\
        --run-covariance-geometry \\
        --run-noise-correlations \\
        --run-aggregation-scaling
"""
from __future__ import annotations

import argparse
import logging
import sys
import time
import traceback
from pathlib import Path

import numpy as np

# Ensure repo root is on path regardless of working directory
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from VisionCore.paths import VISIONCORE_ROOT
from scripts.phase1_fem.preprocessing import (
    load_session,
    build_valid_mask,
    select_primary_units,
    compute_loto_residuals,
    compute_image_repeat_support,
    compute_session_qc,
    compute_unit_qc,
)
from scripts.phase1_fem.geometry import run_covariance_geometry
from scripts.phase1_fem.noise_correlations import run_noise_correlations
from scripts.phase1_fem.aggregation_scaling import run_aggregation_scaling
from scripts.phase1_fem.output_utils import (
    make_output_tree,
    write_csv,
    write_config,
    dict_to_csv_row,
    figure_session_qc_overview,
    figure_eigenspectra_by_session,
    figure_fem_dimensionality_summary,
    figure_shared_vs_image_specific,
    figure_image_shuffle_eye_shuffle_controls,
    figure_aggregation_scaling_curves,
    figure_aggregation_scaling_summary,
    write_pilot_report,
)

logger = logging.getLogger("phase1_fem")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Phase 1 FEM/V1 covariance analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--dataset-configs-path",
        default="multi_basic_120_long_legacy.yaml",
        help="Path to dataset config YAML (relative to experiments/dataset_configs/ or absolute)",
    )
    p.add_argument(
        "--sessions",
        nargs="+",
        default=["Allen:2022-02-16"],
        metavar="SUBJECT:DATE",
        help="Sessions to analyse, e.g. Allen:2022-02-16",
    )
    p.add_argument(
        "--out-dir",
        default="outputs/phase1_fem_covariance",
        help="Root output directory",
    )
    p.add_argument("--use-cached-data", action="store_true", default=False)
    p.add_argument("--bin-ms", type=float, default=10.0, help="Requested bin size in ms")
    p.add_argument("--random-seed", type=int, default=12345)
    p.add_argument("--min-rate-hz", type=float, default=0.5)
    p.add_argument("--min-valid-fraction", type=float, default=0.2)
    p.add_argument("--fixation-radius", type=float, default=1.0)
    p.add_argument("--n-splits", type=int, default=100, help="Split-half iterations")
    p.add_argument("--n-shuffles", type=int, default=200, help="Control shuffle iterations")
    p.add_argument(
        "--aggregation-sampling-unit",
        choices=["valid_rows", "image_time_cells", "image_windows", "trials"],
        default="image_time_cells",
        help="Sampling unit for aggregation scaling",
    )
    p.add_argument(
        "--aggregation-estimator",
        choices=["B_emp_regression", "mcfarland"],
        default="mcfarland",
        help="Estimator object for aggregation scaling",
    )
    p.add_argument(
        "--aggregation-min-fit-samples",
        type=int,
        default=5,
        help="Minimum rows required for estimator fit in aggregation scaling",
    )

    # Module flags
    p.add_argument("--run-qc-only", action="store_true")
    p.add_argument("--run-covariance-geometry", action="store_true", default=False)
    p.add_argument("--run-noise-correlations", action="store_true", default=False)
    p.add_argument("--run-aggregation-scaling", action="store_true", default=False)
    p.add_argument("--run-controls", action="store_true", default=False)
    p.add_argument("--verbose", action="store_true", default=False)
    p.add_argument("--pilot", action="store_true", default=False,
                   help="Pilot mode: enforce single session and write pilot report")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Dataset config resolution
# ---------------------------------------------------------------------------

def _resolve_config(cfg_arg: str) -> str:
    p = Path(cfg_arg)
    if p.is_absolute() and p.exists():
        return str(p)
    # Try relative to experiments/dataset_configs/
    candidate = VISIONCORE_ROOT / "experiments" / "dataset_configs" / cfg_arg
    if candidate.exists():
        return str(candidate)
    # Try relative to cwd
    if p.exists():
        return str(p.resolve())
    raise FileNotFoundError(
        f"Cannot find dataset config '{cfg_arg}'. "
        f"Tried: {candidate}"
    )


# ---------------------------------------------------------------------------
# Sanity check: empirical bridge reproduction (Section 9.2)
# ---------------------------------------------------------------------------

def _sanity_check_b_emp(
    R_resid: np.ndarray,
    eye: np.ndarray,
    valid_mask: np.ndarray,
    n_shuffles: int = 200,
    seed: int = 0,
) -> tuple[bool, str]:
    """
    Check that B_emp split-half geometry > eye-permutation null.

    Returns (passed, details_str).
    """
    from scripts.phase1_fem.estimators import fit_b_emp, _top_k_subspace_overlap

    res = fit_b_emp(R_resid, eye, valid_mask)
    if not res["fit_ok"]:
        return False, "B_emp fit failed — cannot perform sanity check"

    # Observed split-half: compare C_eye geometry across random trial halves.
    NT = R_resid.shape[0]
    rng = np.random.default_rng(seed)
    observed_overlaps = []
    n_splits = 100
    for _ in range(n_splits):
        perm = rng.permutation(NT)
        ha, hb = perm[:NT // 2], perm[NT // 2:]
        r_a = fit_b_emp(R_resid[ha], eye[ha], valid_mask[ha])
        r_b = fit_b_emp(R_resid[hb], eye[hb], valid_mask[hb])
        if not (r_a["fit_ok"] and r_b["fit_ok"]):
            continue
        observed_overlaps.append(_top_k_subspace_overlap(r_a["C_eye"], r_b["C_eye"], k=2))

    if not observed_overlaps:
        return False, "Could not compute split-half subspace overlaps"
    obs_median = float(np.median(observed_overlaps))

    # Permutation null: same split-half overlap metric, but with eye traces
    # trial-permuted before fitting each split.
    null_overlaps = []
    for _ in range(n_shuffles):
        perm = rng.permutation(NT)
        ha, hb = perm[:NT // 2], perm[NT // 2:]

        eye_perm_a = eye[rng.permutation(NT)][ha]
        eye_perm_b = eye[rng.permutation(NT)][hb]

        r_a = fit_b_emp(R_resid[ha], eye_perm_a, valid_mask[ha])
        r_b = fit_b_emp(R_resid[hb], eye_perm_b, valid_mask[hb])
        if not (r_a["fit_ok"] and r_b["fit_ok"]):
            continue
        null_overlaps.append(_top_k_subspace_overlap(r_a["C_eye"], r_b["C_eye"], k=2))

    if not null_overlaps:
        return False, "Permutation null empty — cannot perform sanity check"

    null_p95 = float(np.percentile(null_overlaps, 95))
    passed = obs_median > null_p95
    details = (
        f"Split-half C_eye subspace overlap: observed median={obs_median:.4f}, "
        f"eye-permutation p95={null_p95:.4f}, "
        f"n_obs={len(observed_overlaps)}, n_null={len(null_overlaps)} "
        f"→ {'PASS' if passed else 'FAIL'}"
    )
    return passed, details


def _build_model_object_inventory(root: Path) -> list[dict]:
    """
    Inventory known model-object filenames used for model alignment.

    The current pilot path is empirical-only; this inventory is written so
    model-object plumbing can be completed explicitly in a follow-up.
    """
    expected_patterns = [
        "**/B_model*.npz",
        "**/FEM_PCs*.npz",
        "**/model_FEM_covariance*.npz",
        "**/*model_empirical_alignment*/model_empirical_alignment_summary.json",
        "**/model_object_metadata.csv",
    ]
    rows: list[dict] = []
    for pat in expected_patterns:
        matches = sorted(root.glob(pat))
        if matches:
            for m in matches:
                rows.append(
                    {
                        "pattern": pat,
                        "path": str(m.relative_to(root)),
                        "exists": True,
                        "status": "detected",
                        "note": "Used when supported by current Phase 1 model-alignment plumbing",
                    }
                )
        else:
            rows.append(
                {
                    "pattern": pat,
                    "path": "",
                    "exists": False,
                    "status": "not_found",
                    "note": "No cached object found for this pattern",
                }
            )
    return rows


# ---------------------------------------------------------------------------
# Per-session analysis
# ---------------------------------------------------------------------------

def run_session(
    subject: str,
    date: str,
    cfg_path: str,
    out_root: Path,
    args: argparse.Namespace,
) -> dict:
    """
    Run Phase 1 analyses for a single session. Returns summary dict.
    """
    session = f"{subject}_{date}"
    logger.info(f"=== Session: {session} ===")
    t0 = time.time()

    dirs = make_output_tree(out_root, session)

    # ------------------------------------------------------------------
    # 1. Load data
    # ------------------------------------------------------------------
    logger.info("  Loading data...")
    try:
        data = load_session(
            subject, date, cfg_path,
            use_cached=args.use_cached_data,
            fixation_degree_radius=args.fixation_radius,
            verbose=args.verbose,
        )
    except Exception as e:
        logger.error(f"  Data loading failed: {e}\n{traceback.format_exc()}")
        return {"session": session, "status": "data_load_failed", "error": str(e)}

    robs = data["robs"]
    dfs = data["dfs"]
    eyepos = data["eyepos"]
    image_ids = data["image_ids"]
    fix_dur = data["fix_dur"]
    bin_ms = data["bin_ms"]
    cids = data["cids"]

    logger.info(
        f"  Shapes: robs={robs.shape}, eyepos={eyepos.shape}, "
        f"image_ids={image_ids.shape}, bin_ms={bin_ms:.2f}"
    )

    # ------------------------------------------------------------------
    # 2. Valid mask and unit selection
    # ------------------------------------------------------------------
    valid_mask = build_valid_mask(robs, dfs, eyepos, image_ids)
    unit_mask, unit_stats = select_primary_units(
        robs, dfs, valid_mask, bin_ms,
        min_rate_hz=args.min_rate_hz,
        min_valid_fraction=args.min_valid_fraction,
    )
    logger.info(
        f"  Units: total={robs.shape[2]}, primary={int(unit_mask.sum())}, "
        f"valid_bins={int(valid_mask.sum())}"
    )

    # ------------------------------------------------------------------
    # 3. Image repeat support and QC
    # ------------------------------------------------------------------
    image_repeat_records = compute_image_repeat_support(image_ids, valid_mask)
    session_qc = compute_session_qc(
        session, robs, eyepos, image_ids, dfs, valid_mask,
        unit_mask, unit_stats, bin_ms, image_repeat_records,
    )
    unit_qc_rows = compute_unit_qc(session, unit_stats, unit_mask, cids)

    # Write QC outputs
    sess_qc_dir = dirs["session_qc"]
    write_csv(sess_qc_dir / "session_qc.csv", [dict_to_csv_row(session_qc)])
    write_csv(sess_qc_dir / "unit_qc.csv", [dict_to_csv_row(r) for r in unit_qc_rows])
    write_csv(sess_qc_dir / "image_repeat_support.csv", image_repeat_records)
    logger.info(f"  QC written to {sess_qc_dir}")

    if args.run_qc_only:
        return {"session": session, "status": "qc_only", "qc": session_qc}

    # ------------------------------------------------------------------
    # 4. LOTO residuals (shared preprocessing for all analyses)
    # ------------------------------------------------------------------
    logger.info("  Computing LOTO residuals...")
    R_resid = compute_loto_residuals(robs, image_ids, valid_mask)
    n_resid_valid = int(np.isfinite(R_resid[:, :, 0]).sum())
    logger.info(f"  LOTO residuals: {n_resid_valid} valid (trial, time) pairs")

    # Write residual metadata
    resid_meta = {
        "session": session,
        "residual_type": "leave_one_trial_out_image_time_mean",
        "n_valid_trial_time_pairs": n_resid_valid,
        "fraction_pairs_with_residual": n_resid_valid / max(valid_mask.sum(), 1),
    }
    write_csv(sess_qc_dir / "residual_metadata.csv", [resid_meta])

    results: dict = {"session": session, "status": "ok", "qc": session_qc}

    # ------------------------------------------------------------------
    # 5. Analysis 1: covariance geometry
    # ------------------------------------------------------------------
    if args.run_covariance_geometry:
        logger.info("  Running Analysis 1: covariance geometry...")
        try:
            geom = run_covariance_geometry(
                session=session,
                R_raw=robs,
                R_resid=R_resid,
                eye=eyepos,
                image_ids=image_ids,
                valid_mask=valid_mask,
                unit_mask=unit_mask,
                model_alignment_base_dir=VISIONCORE_ROOT / "outputs" / "jacobian_predictive_framework",
                n_splits=args.n_splits,
                n_shuffles=args.n_shuffles,
                seed=args.random_seed,
            )
        except Exception as e:
            logger.error(f"  Covariance geometry failed: {e}\n{traceback.format_exc()}")
            geom = {"session_metrics": {"session": session, "status": "failed", "error": str(e)}}

        sess_cov_dir = dirs["session_covariance_geometry"]

        # Write CSV outputs
        sm = geom.get("session_metrics", {})
        write_csv(sess_cov_dir / "covariance_geometry_session_metrics.csv",
                  [dict_to_csv_row(sm)])

        # Eigenspectrum CSVs
        for estimator_key, eigen_key in [
            ("B_emp_regression", "eigenspectrum_b_emp"),
            ("mcfarland", "eigenspectrum_mcfarland"),
        ]:
            eig = geom.get(eigen_key, {})
            evals = eig.get("eigenvalues")
            if evals is not None and len(evals) > 0:
                eig_rows = [
                    {
                        "session": session,
                        "estimator": estimator_key,
                        "pc_index": i + 1,
                        "eigenvalue": float(evals[i]),
                        "variance_fraction": float(evals[i] / evals.sum()),
                        "cumulative_fraction": float(evals[: i + 1].sum() / evals.sum()),
                    }
                    for i in range(len(evals))
                ]
                write_csv(
                    sess_cov_dir / f"eigenspectrum_{estimator_key}.csv",
                    eig_rows,
                )

        # Shared vs image-specific
        svi = geom.get("shared_vs_image_specific", {})
        write_csv(
            sess_cov_dir / "shared_vs_image_specific_metrics.csv",
            [dict_to_csv_row({**svi, "session": session})],
        )

        # Cached model alignment metrics
        model_align = geom.get("model_alignment", {})
        basis_rows = model_align.get("basis_rows", [])
        if basis_rows:
            rows = []
            for r in basis_rows:
                rows.append(dict_to_csv_row({
                    "session": session,
                    **r,
                    "source_path": model_align.get("source_path", ""),
                }))
            write_csv(sess_cov_dir / "model_alignment_metrics.csv", rows)
        else:
            write_csv(
                sess_cov_dir / "model_alignment_metrics.csv",
                [dict_to_csv_row({
                    "session": session,
                    "basis_name": "",
                    "status": model_align.get("status", "not_available"),
                    "source_path": model_align.get("source_path", ""),
                })],
            )

        # Reliability
        rel = geom.get("reliability", {})
        rel_row = {
            "session": session,
            "split_half_subspace_overlap": rel.get("split_half_subspace_overlap"),
            "split_half_b_cosine": rel.get("split_half_b_cosine"),
            "reliability_ceiling": rel.get("reliability_ceiling"),
            "status": rel.get("status"),
            "n_splits": args.n_splits,
        }
        write_csv(sess_cov_dir / "reliability_metrics.csv", [dict_to_csv_row(rel_row)])

        # Control distributions
        ctrl_dir = dirs["session_controls"]
        for ctrl_name, ctrl_key in [
            ("eye_shuffle", "eye_shuffle_control"),
            ("image_shuffle", "image_shuffle_control"),
        ]:
            ctrl = geom.get(ctrl_key, {})
            t2 = ctrl.get("shuffle_top2_fractions")
            if t2 is not None and len(t2) > 0:
                ctrl_rows = [
                    {"session": session, "control": ctrl_name, "shuffle_index": i,
                     "top2_fraction": float(t2[i])}
                    for i in range(len(t2))
                ]
                write_csv(ctrl_dir / f"{ctrl_name}_distribution.csv", ctrl_rows)

        results["covariance_geometry"] = geom

        # ------------------------------------------------------------------
        # Sanity check: empirical bridge reproduction (Section 9.2)
        # ------------------------------------------------------------------
        logger.info("  Running sanity check (empirical bridge reproduction)...")
        R_p = R_resid[:, :, unit_mask]
        sanity_ok, sanity_details = _sanity_check_b_emp(
            R_p, eyepos, valid_mask, n_shuffles=min(args.n_shuffles, 100), seed=args.random_seed
        )
        results["sanity_passed"] = sanity_ok
        results["sanity_details"] = sanity_details
        logger.info(f"  Sanity check: {sanity_details}")

        if not sanity_ok:
            logger.warning(
                "  SANITY CHECK FAILED. Stopping before batch. "
                "Check preprocessing vs prior bridge pipeline."
            )

    # ------------------------------------------------------------------
    # 6. Analysis 2: noise correlations (stub)
    # ------------------------------------------------------------------
    if args.run_noise_correlations:
        logger.info("  Running Analysis 2: noise correlations...")
        try:
            noise = run_noise_correlations(
                session=session,
                R_raw=robs,
                R_resid_psth=R_resid,
                eye=eyepos,
                valid_mask=valid_mask,
                unit_mask=unit_mask,
                seed=args.random_seed,
            )
        except Exception as e:
            logger.error(f"  Noise correlations failed: {e}\\n{traceback.format_exc()}")
            noise = {
                "session_metrics": {"session": session, "status": "failed", "error": str(e)},
                "pair_metrics_rows": [],
                "synthetic_control_rows": [],
                "residual_structure_rows": [],
            }

        sess_noise_dir = dirs["session_noise_correlations"]
        write_csv(
            sess_noise_dir / "noise_correlation_session_metrics.csv",
            [dict_to_csv_row(noise.get("session_metrics", {"session": session, "status": "missing"}))],
        )
        write_csv(
            sess_noise_dir / "noise_correlation_pair_metrics.csv",
            [dict_to_csv_row(r) for r in noise.get("pair_metrics_rows", [])],
        )
        write_csv(
            sess_noise_dir / "synthetic_control_metrics.csv",
            [dict_to_csv_row(r) for r in noise.get("synthetic_control_rows", [])],
        )
        write_csv(
            sess_noise_dir / "residual_correlation_structure.csv",
            [dict_to_csv_row(r) for r in noise.get("residual_structure_rows", [])],
        )
        results["noise_correlations"] = noise

    # ------------------------------------------------------------------
    # 7. Analysis 3: aggregation scaling
    # ------------------------------------------------------------------
    if args.run_aggregation_scaling:
        logger.info("  Running Analysis 3: aggregation scaling...")
        try:
            agg = run_aggregation_scaling(
                session=session,
                R_resid=R_resid,
                eye=eyepos,
                image_ids=image_ids,
                valid_mask=valid_mask,
                unit_mask=unit_mask,
                sampling_unit=args.aggregation_sampling_unit,
                estimator=args.aggregation_estimator,
                seed=args.random_seed,
                n_bootstrap=args.n_splits,
                min_fit_samples=args.aggregation_min_fit_samples,
                run_eye_shuffle_null=True,
            )
        except Exception as e:
            logger.error(f"  Aggregation scaling failed: {e}\\n{traceback.format_exc()}")
            agg = {
                "session_metrics": {"session": session, "status": "failed", "error": str(e)},
                "aggregation_curve_rows": [],
                "reliability_vs_n_rows": [],
                "stage4_comparison_rows": [],
            }

        sess_agg_dir = dirs["session_aggregation_scaling"]
        write_csv(
            sess_agg_dir / "aggregation_scaling_session_metrics.csv",
            [dict_to_csv_row(agg.get("session_metrics", {"session": session, "status": "missing"}))],
        )
        write_csv(
            sess_agg_dir / "aggregation_scaling_curves.csv",
            [dict_to_csv_row(r) for r in agg.get("aggregation_curve_rows", [])],
        )
        write_csv(
            sess_agg_dir / "reliability_vs_n_windows.csv",
            [dict_to_csv_row(r) for r in agg.get("reliability_vs_n_rows", [])],
        )
        write_csv(
            sess_agg_dir / "stage4_comparison_metrics.csv",
            [dict_to_csv_row(r) for r in agg.get("stage4_comparison_rows", [])],
        )
        results["aggregation_scaling"] = agg

    elapsed = time.time() - t0
    logger.info(f"  Session done in {elapsed:.1f}s")
    results["elapsed_s"] = elapsed
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    args = _parse_args()

    # Logging
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%H:%M:%S",
    )

    # Resolve paths
    cfg_path = _resolve_config(args.dataset_configs_path)
    out_root = VISIONCORE_ROOT / args.out_dir
    out_root.mkdir(parents=True, exist_ok=True)
    logger.info(f"Output root: {out_root}")
    logger.info(f"Config: {cfg_path}")

    # Top-level dirs
    top_dirs = make_output_tree(out_root)

    # Parse sessions
    sessions: list[tuple[str, str]] = []
    for spec in args.sessions:
        if ":" in spec:
            subject, date = spec.split(":", 1)
        else:
            raise ValueError(f"Session spec must be SUBJECT:DATE, got '{spec}'")
        sessions.append((subject, date))

    # Pilot mode checks
    if args.pilot and len(sessions) > 1:
        logger.error("Pilot mode requires a single session. Use --sessions Allen:2022-02-16")
        return 1

    # Write config
    config_dict = {
        "requested_bin_ms": args.bin_ms,
        "eye_alignment": "linear_interpolation_to_neural_bin_centers",
        "neural_units": "spike_count_or_rate_as_loaded",
        "primary_residual": "leave_one_trial_out_image_time_mean",
        "secondary_residuals": ["raw_rate_normalized", "trial_time_residual"],
        "min_rate_hz": args.min_rate_hz,
        "min_valid_fraction": args.min_valid_fraction,
        "fixation_radius_deg": args.fixation_radius,
        "random_seed": args.random_seed,
        "n_splits": args.n_splits,
        "n_shuffles": args.n_shuffles,
        "aggregation_sampling_unit": args.aggregation_sampling_unit,
        "aggregation_estimator": args.aggregation_estimator,
        "aggregation_min_fit_samples": args.aggregation_min_fit_samples,
        "sessions": [f"{s}:{d}" for s, d in sessions],
        "dataset_configs_path": cfg_path,
        "primary_C_FEM_method": "mcfarland",
        "sensitivity_C_FEM_method": "B_emp_regression",
        "model_alignment_mode": "cached_model_empirical_alignment_summary",
    }
    write_config(top_dirs["configs"] / "phase1_config.yaml", config_dict)

    inventory_rows = _build_model_object_inventory(VISIONCORE_ROOT)
    write_csv(top_dirs["configs"] / "model_object_inventory.csv", inventory_rows)
    write_csv(top_dirs["covariance_geometry"] / "model_object_inventory.csv", inventory_rows)

    # ------------------------------------------------------------------
    # Run sessions
    # ------------------------------------------------------------------
    all_session_qc: list[dict] = []
    all_session_metrics: list[dict] = []
    all_eigenspectrum_records: list[dict] = []
    all_model_alignment_rows: list[dict] = []
    all_noise_session_rows: list[dict] = []
    all_noise_pair_rows: list[dict] = []
    all_noise_synth_rows: list[dict] = []
    all_noise_structure_rows: list[dict] = []
    all_agg_session_rows: list[dict] = []
    all_agg_curve_rows: list[dict] = []
    all_agg_reliability_rows: list[dict] = []
    all_agg_stage4_rows: list[dict] = []
    session_results: dict[str, dict] = {}

    aborted_by_sanity = False
    for subject, date in sessions:
        result = run_session(subject, date, cfg_path, out_root, args)
        session = f"{subject}_{date}"
        session_results[session] = result

        qc = result.get("qc")
        if qc:
            all_session_qc.append(qc)

        if args.run_covariance_geometry and "covariance_geometry" in result:
            geom = result["covariance_geometry"]
            sm = geom.get("session_metrics")
            if sm:
                all_session_metrics.append(sm)

            model_align = geom.get("model_alignment", {})
            basis_rows = model_align.get("basis_rows", [])
            if basis_rows:
                for r in basis_rows:
                    all_model_alignment_rows.append(
                        dict_to_csv_row({
                            "session": session,
                            **r,
                            "source_path": model_align.get("source_path", ""),
                        })
                    )
            else:
                all_model_alignment_rows.append(
                    dict_to_csv_row({
                        "session": session,
                        "basis_name": "",
                        "status": model_align.get("status", "not_available"),
                        "source_path": model_align.get("source_path", ""),
                    })
                )

            # Collect eigenspectrum records for cross-session figure
            for est_key, eigen_key in [
                ("B_emp_regression", "eigenspectrum_b_emp"),
                ("mcfarland", "eigenspectrum_mcfarland"),
            ]:
                eig = geom.get(eigen_key, {})
                evals = eig.get("eigenvalues")
                if evals is not None and len(evals) > 0:
                    all_eigenspectrum_records.append({
                        "session": session,
                        "estimator": est_key,
                        "eigenvalues": evals,
                        **{k: v for k, v in eig.items() if k != "eigenvalues"},
                    })

        if args.run_covariance_geometry and result.get("sanity_passed") is False:
            logger.error(
                "Sanity gate failed for %s. Stopping remaining sessions before batch progression.",
                session,
            )
            aborted_by_sanity = True
            break

        if args.run_noise_correlations and "noise_correlations" in result:
            noise = result["noise_correlations"]
            sm = noise.get("session_metrics")
            if sm:
                all_noise_session_rows.append(sm)
            all_noise_pair_rows.extend(noise.get("pair_metrics_rows", []))
            all_noise_synth_rows.extend(noise.get("synthetic_control_rows", []))
            all_noise_structure_rows.extend(noise.get("residual_structure_rows", []))

        if args.run_aggregation_scaling and "aggregation_scaling" in result:
            agg = result["aggregation_scaling"]
            sm = agg.get("session_metrics")
            if sm:
                all_agg_session_rows.append(sm)
            all_agg_curve_rows.extend(agg.get("aggregation_curve_rows", []))
            all_agg_reliability_rows.extend(agg.get("reliability_vs_n_rows", []))
            all_agg_stage4_rows.extend(agg.get("stage4_comparison_rows", []))

    # ------------------------------------------------------------------
    # Write aggregated QC outputs
    # ------------------------------------------------------------------
    write_csv(top_dirs["qc"] / "session_qc.csv",
              [dict_to_csv_row(r) for r in all_session_qc])

    # ------------------------------------------------------------------
    # Write aggregated covariance geometry outputs
    # ------------------------------------------------------------------
    if args.run_covariance_geometry and all_session_metrics:
        write_csv(
            top_dirs["covariance_geometry"] / "covariance_geometry_session_metrics.csv",
            [dict_to_csv_row(r) for r in all_session_metrics],
        )
        write_csv(
            top_dirs["covariance_geometry"] / "model_alignment_metrics.csv",
            all_model_alignment_rows,
        )

    # ------------------------------------------------------------------
    # Figures
    # ------------------------------------------------------------------
    fig_dir = top_dirs["figures"]

    if all_session_qc:
        figure_session_qc_overview(
            all_session_qc,
            fig_dir / "session_qc_overview.png",
        )
        write_csv(
            fig_dir / "session_qc_overview.csv",
            [dict_to_csv_row(r) for r in all_session_qc],
        )

    if args.run_covariance_geometry and all_eigenspectrum_records:
        figure_eigenspectra_by_session(
            all_eigenspectrum_records,
            fig_dir / "covariance_eigenspectra_by_session.png",
        )

    if args.run_covariance_geometry and all_session_metrics:
        figure_fem_dimensionality_summary(
            all_session_metrics,
            [],
            fig_dir / "fem_covariance_dimensionality_summary.png",
        )
        write_csv(
            fig_dir / "fem_covariance_dimensionality_summary.csv",
            [dict_to_csv_row(r) for r in all_session_metrics],
        )

    # ------------------------------------------------------------------
    # Write aggregated noise-correlation outputs
    # ------------------------------------------------------------------
    if args.run_noise_correlations and all_noise_session_rows:
        write_csv(
            top_dirs["noise_correlations"] / "noise_correlation_session_metrics.csv",
            [dict_to_csv_row(r) for r in all_noise_session_rows],
        )
        write_csv(
            top_dirs["noise_correlations"] / "noise_correlation_pair_metrics.csv",
            [dict_to_csv_row(r) for r in all_noise_pair_rows],
        )
        write_csv(
            top_dirs["noise_correlations"] / "synthetic_control_metrics.csv",
            [dict_to_csv_row(r) for r in all_noise_synth_rows],
        )
        write_csv(
            top_dirs["noise_correlations"] / "residual_correlation_structure.csv",
            [dict_to_csv_row(r) for r in all_noise_structure_rows],
        )

        svi_rows = []
        for r in all_session_metrics:
            svi_rows.append({
                "session": r.get("session"),
                "mean_r2_shared": r.get("mean_r2_shared"),
                "mean_r2_image_specific": r.get("mean_r2_image_specific"),
                "r2_delta_image_vs_shared": r.get("shared_vs_img_r2_delta"),
            })
        figure_shared_vs_image_specific(svi_rows, fig_dir / "shared_vs_image_specific_geometry.png")
        write_csv(fig_dir / "shared_vs_image_specific_geometry.csv",
                  [dict_to_csv_row(r) for r in svi_rows])

        figure_image_shuffle_eye_shuffle_controls(
            all_session_metrics,
            fig_dir / "image_shuffle_eye_shuffle_controls.png",
        )
        write_csv(
            fig_dir / "image_shuffle_eye_shuffle_controls.csv",
            [dict_to_csv_row(r) for r in all_session_metrics],
        )

    # ------------------------------------------------------------------
    # Write aggregated aggregation-scaling outputs
    # ------------------------------------------------------------------
    if args.run_aggregation_scaling and all_agg_session_rows:
        write_csv(
            top_dirs["aggregation_scaling"] / "aggregation_scaling_session_metrics.csv",
            [dict_to_csv_row(r) for r in all_agg_session_rows],
        )
        write_csv(
            top_dirs["aggregation_scaling"] / "aggregation_scaling_curves.csv",
            [dict_to_csv_row(r) for r in all_agg_curve_rows],
        )
        write_csv(
            top_dirs["aggregation_scaling"] / "reliability_vs_n_windows.csv",
            [dict_to_csv_row(r) for r in all_agg_reliability_rows],
        )
        write_csv(
            top_dirs["aggregation_scaling"] / "stage4_comparison_metrics.csv",
            [dict_to_csv_row(r) for r in all_agg_stage4_rows],
        )

        figure_aggregation_scaling_curves(
            all_agg_curve_rows,
            fig_dir / "aggregation_scaling_curves.png",
        )
        write_csv(
            fig_dir / "aggregation_scaling_curves.csv",
            [dict_to_csv_row(r) for r in all_agg_curve_rows],
        )

        figure_aggregation_scaling_summary(
            all_agg_session_rows,
            fig_dir / "aggregation_scaling_summary.png",
        )
        write_csv(
            fig_dir / "aggregation_scaling_summary.csv",
            [dict_to_csv_row(r) for r in all_agg_session_rows],
        )

    # ------------------------------------------------------------------
    # Pilot report
    # ------------------------------------------------------------------
    if args.pilot and len(sessions) == 1:
        subject, date = sessions[0]
        session = f"{subject}_{date}"
        res = session_results.get(session, {})

        geom = res.get("covariance_geometry", {})
        sm = geom.get("session_metrics", {})
        svi = geom.get("shared_vs_image_specific", {})
        rel = geom.get("reliability", {})

        write_pilot_report(
            path=top_dirs["summaries"] / "pilot_phase1_covariance_report.md",
            session=session,
            session_qc=res.get("qc", {}),
            session_metrics=sm,
            shared_vs_img=svi,
            reliability=rel,
            sanity_passed=res.get("sanity_passed", False),
            sanity_details=res.get("sanity_details", "not run"),
        )
        logger.info(f"Pilot report written to {top_dirs['summaries']}")

    # ------------------------------------------------------------------
    # Final status
    # ------------------------------------------------------------------
    n_ok = sum(1 for r in session_results.values() if r.get("status") not in ("data_load_failed",))
    logger.info(f"Done. {n_ok}/{len(sessions)} sessions completed successfully.")
    logger.info(f"Outputs in: {out_root}")

    if args.pilot and len(sessions) == 1:
        res = list(session_results.values())[0]
        sanity_ok = res.get("sanity_passed", None)
        if sanity_ok is False:
            logger.warning(
                "Pilot sanity check FAILED. Do NOT proceed to batch. "
                "Reconcile preprocessing with prior bridge pipeline first."
            )
            return 2
        elif sanity_ok is True:
            logger.info("Pilot sanity check PASSED. Safe to proceed to batch.")

    if aborted_by_sanity:
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
